### PR TITLE
add block2 message option

### PR DESCRIPTION
**Pull request by Jiloc**

### CODE REVIEW

**Comment by okleine** [comment]
Thanks for our effort! I think, its a good idea to implement the blockwise extension. However, your pull request is only about the block 2 option and without any further logic, i.e. separation and re-composition of messages . The pure presence of the option may be misleading because as a user one would assume more. Would you consider implementing the blockwise extension as a whole? Unfortunatly I didn't have the time to do it, yet.

**Comment by okleine** [comment]
I will take your additions as a basis for rudimentary support for the block2 option (on the client side only until further notice). Thank you again!

**Comment by Jiloc** [comment]
Thank YOU for starting this project and excuse me but i forgot about this
merge request and i did not answer!
Il 08/mag/2015 17:24, "Oliver Kleine" <notifications@github.com> ha scritto:
>
> I will take your additions as a basis for rudimentary support for the
block2 option (on the client side only until further notice). Thank you
again!

**Comment by okleine** [comment]
You might want to have a look at the "blockwise" branch. I added rather simple support for blockwise transfer on the client side. A client always accepts the blocksize that was given by the server (in its first response). Upon reception of the first block the client requests further blocks automatically. The ClientCallback is invoked upon reception of the complete payload.

**Pull request merged**
